### ISSUE TITLE
Wesh t9d tkon fiha fraude had l9adya ??

### ISSUE THREAD

**Issue by Iory-100** [hlnajz/skip-rosetta-stone-foundations-#1]

**Comment by hlnajz** [comment]
No, Better use this repoL [RosettaWizard](https://github.com/hlnajz/rosettaWizard), here's the official letter from rosetta in the image
![WhatsApp Image 2024-12-11 at 1 00 42 PM](https://github.com/user-attachments/assets/83d47d1a-9c62-4a80-bc88-cc0cc6414a20)
