### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by xXAloneX** [hlnajz/skip-rosetta-stone-foundations-#3]
![image](https://github.com/user-attachments/assets/d09a0087-99c2-4f43-991e-5e1859223a92)
IT STAYS LIKE THIS I DID THE EXERCICE

**Comment by hlnajz** [comment]
Hello brother I told you the script is closed by Rosetta stone but there's the extension is working RoesttaWizard i will make video tomorrow unchallah how to work with it in my channel hlnajz on YouTube
